<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            // Development Services
            [
                'title' => 'Web Development',
                'short_description' => 'Custom websites and web applications built with modern technologies.',
                'description' => 'We create powerful, scalable web applications using cutting-edge technologies like Laravel, React, Vue.js, and Node.js. From simple landing pages to complex enterprise systems, we deliver solutions that drive business growth. Our development process includes thorough planning, agile development, rigorous testing, and ongoing support.',
                'icon' => 'fas fa-laptop-code',
                'features' => json_encode(['Custom Web Applications', 'Responsive Design', 'Performance Optimization', 'Security Best Practices', 'SEO-Friendly Architecture', 'API Integration']),
                'category' => 'Development',
                'is_active' => true,
                'is_featured' => true,
                'order' => 1,
            ],
            [
                'title' => 'Mobile Development',
                'short_description' => 'Native and cross-platform mobile apps for iOS and Android.',
                'description' => 'Build engaging mobile experiences with our expert mobile development team. We specialize in both native iOS/Android development and cross-platform solutions using React Native and Flutter. Our apps are designed for performance, usability, and scalability to help you reach customers on any device.',
                'icon' => 'fas fa-mobile-alt',
                'features' => json_encode(['iOS Development', 'Android Development', 'React Native', 'Flutter Apps', 'App Store Optimization', 'Push Notifications']),
                'category' => 'Development',
                'is_active' => true,
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'title' => 'E-Commerce Solutions',
                'short_description' => 'Scalable online stores with payment integration and analytics.',
                'description' => 'Launch and grow your online business with our comprehensive e-commerce solutions. We build custom shopping experiences with secure payment processing, inventory management, and powerful analytics. Whether you need a simple store or a multi-vendor marketplace, we have you covered.',
                'icon' => 'fas fa-shopping-cart',
                'features' => json_encode(['Custom Storefronts', 'Payment Gateway Integration', 'Inventory Management', 'Order Processing', 'Customer Analytics', 'Multi-currency Support']),
                'category' => 'Development',
                'is_active' => true,
                'is_featured' => false,
                'order' => 3,
            ],
            [
                'title' => 'API Development',
                'short_description' => 'RESTful and GraphQL APIs for seamless system integration.',
                'description' => 'Connect your systems and applications with robust, well-documented APIs. We design and build RESTful and GraphQL APIs that are secure, scalable, and easy to integrate. From internal microservices to public APIs, we ensure your data flows smoothly between platforms.',
                'icon' => 'fas fa-cogs',
                'features' => json_encode(['RESTful APIs', 'GraphQL', 'API Documentation', 'Authentication & Security', 'Rate Limiting', 'Versioning']),
                'category' => 'Development',
                'is_active' => true,
                'is_featured' => false,
                'order' => 4,
            ],
            [
                'title' => 'Database Design',
                'short_description' => 'Optimized database architecture for performance and scalability.',
                'description' => 'Your data is your most valuable asset. We design database architectures that ensure data integrity, optimize performance, and scale with your business. From relational databases like MySQL and PostgreSQL to NoSQL solutions like MongoDB, we choose the right tool for your needs.',
                'icon' => 'fas fa-database',
                'features' => json_encode(['Schema Design', 'Query Optimization', 'Data Migration', 'Backup Strategies', 'Replication Setup', 'Performance Tuning']),
                'category' => 'Development',
                'is_active' => true,
                'is_featured' => false,
                'order' => 5,
            ],
            [
                'title' => 'System Integration',
                'short_description' => 'Connect your tools and platforms for unified workflows.',
                'description' => 'Break down silos and streamline your operations with our system integration services. We connect disparate systems, automate data synchronization, and create unified workflows that save time and reduce errors. From CRM to ERP integrations, we make your technology work together.',
                'icon' => 'fas fa-plug',
                'features' => json_encode(['CRM Integration', 'ERP Connectivity', 'Data Synchronization', 'Workflow Automation', 'Third-party APIs', 'Legacy System Integration']),
                'category' => 'Development',
                'is_active' => true,
                'is_featured' => false,
                'order' => 6,
            ],

            // Cloud & DevOps Services
            [
                'title' => 'AWS Solutions',
                'short_description' => 'Comprehensive AWS infrastructure setup and optimization.',
                'description' => 'Leverage the power of Amazon Web Services with our expert AWS solutions. We help you design, deploy, and manage cloud infrastructure that is secure, scalable, and cost-effective. From EC2 and S3 to Lambda and RDS, we optimize your AWS environment for peak performance.',
                'icon' => 'fab fa-aws',
                'features' => json_encode(['Infrastructure Design', 'EC2 & Lambda', 'S3 & CloudFront', 'RDS Management', 'Cost Optimization', 'Security & Compliance']),
                'category' => 'Cloud & DevOps',
                'is_active' => true,
                'is_featured' => true,
                'order' => 7,
            ],
            [
                'title' => 'Container & Kubernetes',
                'short_description' => 'Docker containerization and Kubernetes orchestration.',
                'description' => 'Modernize your application deployment with containerization. We help you package applications in Docker containers and orchestrate them with Kubernetes for reliable, scalable deployments. Simplify your DevOps workflow and achieve faster time to market.',
                'icon' => 'fab fa-docker',
                'features' => json_encode(['Docker Setup', 'Kubernetes Clusters', 'Helm Charts', 'Service Mesh', 'Container Security', 'Auto-scaling']),
                'category' => 'Cloud & DevOps',
                'is_active' => true,
                'is_featured' => false,
                'order' => 8,
            ],
            [
                'title' => 'CI/CD Pipelines',
                'short_description' => 'Automated build, test, and deployment pipelines.',
                'description' => 'Accelerate your development with continuous integration and continuous deployment. We set up automated pipelines that build, test, and deploy your code with every commit. Catch bugs early, deploy faster, and maintain high code quality with our CI/CD solutions.',
                'icon' => 'fas fa-infinity',
                'features' => json_encode(['Jenkins Setup', 'GitHub Actions', 'GitLab CI', 'Automated Testing', 'Deployment Automation', 'Environment Management']),
                'category' => 'Cloud & DevOps',
                'is_active' => true,
                'is_featured' => false,
                'order' => 9,
            ],
            [
                'title' => 'Cloud Security',
                'short_description' => 'Security audits and compliance for cloud infrastructure.',
                'description' => 'Protect your cloud assets with our comprehensive security services. We conduct security audits, implement best practices, and ensure compliance with industry standards like SOC 2, HIPAA, and GDPR. Keep your data safe and your customers trust intact.',
                'icon' => 'fas fa-shield-alt',
                'features' => json_encode(['Security Audits', 'Penetration Testing', 'Compliance Setup', 'IAM Configuration', 'Encryption', 'Monitoring & Alerts']),
                'category' => 'Cloud & DevOps',
                'is_active' => true,
                'is_featured' => false,
                'order' => 10,
            ],
            [
                'title' => 'Server Management',
                'short_description' => '24/7 monitoring, maintenance, and optimization.',
                'description' => 'Keep your servers running smoothly with our managed services. We provide 24/7 monitoring, regular maintenance, performance optimization, and rapid incident response. Focus on your business while we handle the infrastructure.',
                'icon' => 'fas fa-server',
                'features' => json_encode(['24/7 Monitoring', 'Patch Management', 'Performance Tuning', 'Incident Response', 'Log Analysis', 'Capacity Planning']),
                'category' => 'Cloud & DevOps',
                'is_active' => true,
                'is_featured' => false,
                'order' => 11,
            ],
            [
                'title' => 'Disaster Recovery',
                'short_description' => 'Backup strategies and disaster recovery plans.',
                'description' => 'Prepare for the unexpected with our disaster recovery solutions. We design and implement backup strategies, create recovery plans, and test failover procedures to ensure business continuity. Minimize downtime and data loss with our expertise.',
                'icon' => 'fas fa-sync-alt',
                'features' => json_encode(['Backup Automation', 'Recovery Plans', 'Failover Testing', 'Data Replication', 'RTO/RPO Planning', 'Business Continuity']),
                'category' => 'Cloud & DevOps',
                'is_active' => true,
                'is_featured' => false,
                'order' => 12,
            ],

            // AI & Data Services
            [
                'title' => 'Machine Learning',
                'short_description' => 'Custom ML models for prediction and automation.',
                'description' => 'Harness the power of machine learning to transform your business. We build custom ML models for prediction, classification, anomaly detection, and process automation. From data preparation to model deployment, we handle the entire ML lifecycle.',
                'icon' => 'fas fa-robot',
                'features' => json_encode(['Predictive Models', 'Classification', 'Anomaly Detection', 'Model Training', 'Feature Engineering', 'Model Deployment']),
                'category' => 'AI & Data',
                'is_active' => true,
                'is_featured' => true,
                'order' => 13,
            ],
            [
                'title' => 'AI Chatbots',
                'short_description' => 'Intelligent conversational AI for customer engagement.',
                'description' => 'Enhance customer experience with AI-powered chatbots. We build intelligent conversational interfaces that handle customer inquiries, provide support, and drive engagement 24/7. Integrate with your existing systems for seamless automation.',
                'icon' => 'fas fa-comments',
                'features' => json_encode(['Natural Language Processing', 'Multi-channel Support', 'Intent Recognition', 'Context Awareness', 'CRM Integration', 'Analytics Dashboard']),
                'category' => 'AI & Data',
                'is_active' => true,
                'is_featured' => false,
                'order' => 14,
            ],
            [
                'title' => 'Data Analytics',
                'short_description' => 'Transform raw data into actionable insights.',
                'description' => 'Make data-driven decisions with our analytics solutions. We help you collect, process, and analyze data to uncover insights that drive business growth. From dashboards to custom reports, we make your data accessible and actionable.',
                'icon' => 'fas fa-chart-bar',
                'features' => json_encode(['Data Visualization', 'Custom Dashboards', 'KPI Tracking', 'Trend Analysis', 'Reporting Automation', 'Data Warehousing']),
                'category' => 'AI & Data',
                'is_active' => true,
                'is_featured' => false,
                'order' => 15,
            ],
            [
                'title' => 'Computer Vision',
                'short_description' => 'Image recognition and visual AI solutions.',
                'description' => 'See the world through AI with our computer vision solutions. We develop image recognition, object detection, facial recognition, and video analysis systems. From quality inspection to security applications, we bring visual intelligence to your products.',
                'icon' => 'fas fa-eye',
                'features' => json_encode(['Object Detection', 'Image Classification', 'Facial Recognition', 'Video Analytics', 'OCR Solutions', 'Quality Inspection']),
                'category' => 'AI & Data',
                'is_active' => true,
                'is_featured' => false,
                'order' => 16,
            ],
            [
                'title' => 'NLP Solutions',
                'short_description' => 'Natural language processing for text analysis.',
                'description' => 'Understand and process human language with our NLP solutions. We build systems for sentiment analysis, text classification, entity extraction, and language translation. Unlock insights from unstructured text data at scale.',
                'icon' => 'fas fa-language',
                'features' => json_encode(['Sentiment Analysis', 'Text Classification', 'Entity Extraction', 'Language Translation', 'Text Summarization', 'Search Enhancement']),
                'category' => 'AI & Data',
                'is_active' => true,
                'is_featured' => false,
                'order' => 17,
            ],
            [
                'title' => 'Data Engineering',
                'short_description' => 'Build robust data pipelines for big data processing.',
                'description' => 'Build the foundation for data-driven success with our data engineering services. We design and implement data pipelines, data lakes, and data warehouses that handle big data at scale. Enable real-time analytics and machine learning with reliable data infrastructure.',
                'icon' => 'fas fa-project-diagram',
                'features' => json_encode(['ETL Pipelines', 'Data Lakes', 'Stream Processing', 'Data Quality', 'Schema Management', 'Big Data Tools']),
                'category' => 'AI & Data',
                'is_active' => true,
                'is_featured' => false,
                'order' => 18,
            ],

            // Design & UX Services
            [
                'title' => 'UI/UX Design',
                'short_description' => 'Beautiful, intuitive, and conversion-focused designs.',
                'description' => 'Create exceptional user experiences with our UI/UX design services. We combine aesthetic beauty with functional design to create interfaces that users love. From wireframes to high-fidelity prototypes, we design with your users in mind.',
                'icon' => 'fas fa-pencil-ruler',
                'features' => json_encode(['User Research', 'Wireframing', 'Visual Design', 'Interaction Design', 'Usability Testing', 'Design Handoff']),
                'category' => 'Design & UX',
                'is_active' => true,
                'is_featured' => true,
                'order' => 19,
            ],
            [
                'title' => 'Design Systems',
                'short_description' => 'Scalable component libraries for consistency.',
                'description' => 'Build design consistency at scale with a comprehensive design system. We create component libraries, design tokens, and documentation that ensure brand consistency across all your products. Speed up development and maintain design quality.',
                'icon' => 'fas fa-layer-group',
                'features' => json_encode(['Component Libraries', 'Design Tokens', 'Style Guides', 'Documentation', 'Figma Libraries', 'Code Integration']),
                'category' => 'Design & UX',
                'is_active' => true,
                'is_featured' => false,
                'order' => 20,
            ],
            [
                'title' => 'Prototyping',
                'short_description' => 'Interactive prototypes to validate ideas.',
                'description' => 'Test your ideas before investing in development. We create interactive prototypes that simulate the real product experience. Validate concepts, gather feedback, and iterate quickly to find the right solution before writing code.',
                'icon' => 'fas fa-object-group',
                'features' => json_encode(['Low-fidelity Prototypes', 'High-fidelity Prototypes', 'Interactive Demos', 'User Testing', 'Stakeholder Presentations', 'Rapid Iteration']),
                'category' => 'Design & UX',
                'is_active' => true,
                'is_featured' => false,
                'order' => 21,
            ],
            [
                'title' => 'Brand Identity',
                'short_description' => 'Logo design and complete brand guidelines.',
                'description' => 'Define your visual identity with our branding services. We create logos, color palettes, typography systems, and comprehensive brand guidelines that communicate your values and resonate with your audience.',
                'icon' => 'fas fa-paint-brush',
                'features' => json_encode(['Logo Design', 'Color Palette', 'Typography', 'Brand Guidelines', 'Visual Assets', 'Brand Strategy']),
                'category' => 'Design & UX',
                'is_active' => true,
                'is_featured' => false,
                'order' => 22,
            ],
            [
                'title' => 'User Research',
                'short_description' => 'Understand users through interviews and testing.',
                'description' => 'Design with confidence by understanding your users deeply. We conduct user interviews, surveys, usability tests, and analytics analysis to uncover user needs, pain points, and opportunities. Let data guide your design decisions.',
                'icon' => 'fas fa-user-check',
                'features' => json_encode(['User Interviews', 'Surveys', 'Usability Testing', 'A/B Testing', 'Analytics Review', 'Persona Development']),
                'category' => 'Design & UX',
                'is_active' => true,
                'is_featured' => false,
                'order' => 23,
            ],
            [
                'title' => 'Accessibility',
                'short_description' => 'WCAG-compliant designs for all users.',
                'description' => 'Make your products accessible to everyone. We ensure your designs meet WCAG guidelines and accessibility best practices. From color contrast to screen reader compatibility, we help you reach the widest possible audience.',
                'icon' => 'fas fa-universal-access',
                'features' => json_encode(['WCAG Compliance', 'Accessibility Audits', 'Screen Reader Testing', 'Keyboard Navigation', 'Color Contrast', 'Inclusive Design']),
                'category' => 'Design & UX',
                'is_active' => true,
                'is_featured' => false,
                'order' => 24,
            ],
        ];

        foreach ($services as $service) {
            Service::create($service);
        }
    }
}
